spring:
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            use-new-id-generator-mappings: true
            ddl-auto: create
        properties.hibernate:
            format_sql: true
            jdbc.batch_size: 5
            # 같은 타입의 batch가 있을 경우 합치는 옵션
            # order_inserts: true
#            use_sql_comments: true
# logging.level.org.hibernate:
#        SQL: DEBUG
#        type.descriptor.sql.BasicBinder: TRACE
