spring:
    jpa:
        hibernate:
            use-new-id-generator-mappings: true
            ddl-auto: create
            format_sql: true
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect

