spring:
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            use-new-id-generator-mappings: true
            ddl-auto: create-drop
        properties.hibernate:
            format_sql: true
            use_sql_comments: true

logging.level.org.hibernate:
                SQL: DEBUG
                type.descriptor.sql.BasicBinder: TRACE
